# Generated by Django 5.2.15 on 2026-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentchunk',
            name='chunk_index',
            field=models.PositiveIntegerField(help_text='0-based, monotonically increasing per document.'),
        ),
        migrations.AlterField(
            model_name='contentchunk',
            name='section_identifier',
            field=models.CharField(blank=True, help_text='e.g. "4.3.2". Null if no heading structure was detected.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagramasset',
            name='bounding_box',
            field=models.JSONField(blank=True, help_text='{x, y, width, height} in PDF points.', null=True),
        ),
        migrations.AlterField(
            model_name='diagramasset',
            name='caption',
            field=models.TextField(blank=True, help_text='Nearest text identified as a figure caption, if any.', null=True),
        ),
        migrations.AlterField(
            model_name='diagramasset',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Text detected inside the image, if any.', null=True),
        ),
    ]
