# Generated by Django 5.2.15 on 2026-06-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0002_alter_contentchunk_chunk_index_and_more'),
        ('chunks', '0002_alter_contentchunk_embedding_dimensions'),
    ]

    operations = [
    ]
