# Generated by Django 5.2.15 on 2026-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, help_text='Set when status=FAILED. Human-readable failure description.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='Display name. Defaults to original_filename if not supplied at upload.', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Populated after extract_text_and_tables completes.', null=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='has_images',
            field=models.BooleanField(default=False, help_text='True if ≥1 DiagramAsset was extracted from this page.'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='has_tables',
            field=models.BooleanField(default=False, help_text='True if ≥1 table was detected on this page.'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='page_number',
            field=models.PositiveIntegerField(help_text='1-indexed page number.'),
        ),
    ]
